/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package br.com.coau.telas;

import br.com.coau.persistence.JPADao;
import br.com.coau.persistence.Livros;
import br.com.coau.telas.TelaAlugarLivro;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Warley
 */
public class TelaCadastroLivros extends javax.swing.JInternalFrame {

    private TelaAlugarLivro telaAlugarLivro;
    private String tipoUsuario;

    /**
     * Creates new form TelaCadastroLivros
     */
    public TelaCadastroLivros() {
        initComponents();
        listarTabela();
        atualizarTblLivros();

    }

    public TelaCadastroLivros(TelaAlugarLivro telaAlugarLivro) {
        this.telaAlugarLivro = telaAlugarLivro;
        initComponents();
        listarTabela();
        atualizarTblLivros();
    }

    private void atualizarTblLivros() {
        JPADao jpd = new JPADao();
        List<Livros> livros = jpd.listarLivros();

        DefaultTableModel model = (DefaultTableModel) tblLivros.getModel();
        model.setRowCount(0);

        for (Livros livro : livros) {
            model.addRow(new Object[]{
                livro.getIdliv(),
                livro.getNomeliv(),
                livro.getAutorliv(),
                livro.getAssuntoliv(),
                livro.getEditoraliv()
            });
        }
    }

    private void listarTabela() {
        atualizarTblLivros();
    }

    private void pesquisarLivro() {
        String nome = txtPesquisarLivro.getText();
        JPADao jpd = new JPADao();
        List<Livros> livros = jpd.pesquisarlivro(nome);
        DefaultTableModel tabela = (DefaultTableModel) tblLivros.getModel();
        tabela.setRowCount(0);
        if (livros != null && !livros.isEmpty()) {
            for (Livros l : livros) {
                tabela.addRow(new Object[]{
                    l.getIdliv(),
                    l.getNomeliv(),
                    l.getAutorliv(),
                    l.getAssuntoliv(),
                    l.getEditoraliv()
                });
            }
        } else {
            System.out.println("Nenhum Livro encontrado para este Título !");
        }

    }

    public void setar_campos() {
        int setar = tblLivros.getSelectedRow();
        txtTitulo.setText(tblLivros.getModel().getValueAt(setar, 1).toString());
        txtAutor.setText(tblLivros.getModel().getValueAt(setar, 2).toString());
        txtAssunto.setText(tblLivros.getModel().getValueAt(setar, 3).toString());
        txtEditora.setText(tblLivros.getModel().getValueAt(setar, 4).toString());

        //desabilitar o botão adicionar
        btnAdicionar.setEnabled(false);

    }

    public long getLivroSelecionadoId() {
        int selectedRow = tblLivros.getSelectedRow();
        if (selectedRow != -1) {
            return (Long) tblLivros.getModel().getValueAt(selectedRow, 0);
        }
        return -1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        btnConsultar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        txtAutor = new javax.swing.JTextField();
        txtAssunto = new javax.swing.JTextField();
        txtEditora = new javax.swing.JTextField();
        btnAdicionar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblLivros = new javax.swing.JTable();
        txtPesquisarLivro = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jLabel6.setText("ID");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/read.png"))); // NOI18N
        btnConsultar.setToolTipText("Consultar");
        btnConsultar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConsultar.setPreferredSize(new java.awt.Dimension(80, 80));

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Cadastro e Edição de Livros");
        setMinimumSize(new java.awt.Dimension(100, 100));

        jLabel2.setText("Título");

        jLabel3.setText("Autor");

        jLabel4.setText("Assunto");

        jLabel5.setText("Editora");

        txtTitulo.setToolTipText("Nome do Livro");

        txtAutor.setToolTipText("Autor do Livro");

        txtAssunto.setToolTipText("Assunto do livro");

        txtEditora.setToolTipText("Editora do livro");

        btnAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/create.png"))); // NOI18N
        btnAdicionar.setToolTipText("Adicionar Livro");
        btnAdicionar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdicionar.setPreferredSize(new java.awt.Dimension(80, 80));
        btnAdicionar.setRequestFocusEnabled(false);
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/update.png"))); // NOI18N
        btnEditar.setToolTipText("Editar Livro");
        btnEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditar.setPreferredSize(new java.awt.Dimension(80, 80));
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnDeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/delete.png"))); // NOI18N
        btnDeletar.setToolTipText("Deletar Livro");
        btnDeletar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDeletar.setPreferredSize(new java.awt.Dimension(80, 80));
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });

        tblLivros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "TÍTULO", "AUTOR", "ASSUNTO", "EDITORA"
            }
        ));
        tblLivros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLivrosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblLivros);

        txtPesquisarLivro.setToolTipText("Pesquisa pelo Título do Livro");
        txtPesquisarLivro.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtPesquisarLivroCaretUpdate(evt);
            }
        });

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/pesquisa1.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(80, 80, 80)
                                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtTitulo)
                            .addComponent(txtAutor)
                            .addComponent(txtAssunto)
                            .addComponent(txtEditora, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtPesquisarLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7)))))
                .addContainerGap(142, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPesquisarLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtAssunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtEditora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        setBounds(0, 0, 650, 500);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        //Adicionando um livro
        Livros l = new Livros();
        try {
            l.setNomeliv(txtTitulo.getText());
            l.setAutorliv(txtAutor.getText());
            l.setAssuntoliv(txtAssunto.getText());
            l.setEditoraliv(txtEditora.getText());
            l.setDisponivelliv(true);

            JPADao jpd = new JPADao();
            jpd.CadastarLivros(l);
            JOptionPane.showMessageDialog(this, "Cadastro Realizado com Sucesso!");
            atualizarTblLivros();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocorreu uma falha:\n" + e.getMessage());
        }
        //Codigo abaixo para limpar a tela apos final cadastro
        txtTitulo.setText("");
        txtAutor.setText("");
        txtAssunto.setText("");
        txtEditora.setText("");
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        int setar = tblLivros.getSelectedRow();
        if (setar != -1) {
            long id = (Long) tblLivros.getModel().getValueAt(setar, 0); // Assuming ID is in the first column
            String titulo = txtTitulo.getText();
            String autor = txtAutor.getText();
            String assunto = txtAssunto.getText();
            String editora = txtEditora.getText();

            JPADao jpd = new JPADao();
            jpd.editarLivro(titulo, autor, assunto, editora, id);
            JOptionPane.showMessageDialog(this, "Livro atualizado com sucesso!");
            atualizarTblLivros();
            txtTitulo.setText("");
            txtAutor.setText("");
            txtAssunto.setText("");
            txtEditora.setText("");
            btnAdicionar.setEnabled(true);
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um Livro para editar.");
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void txtPesquisarLivroCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtPesquisarLivroCaretUpdate
        // TODO add your handling code here:
        pesquisarLivro();
    }//GEN-LAST:event_txtPesquisarLivroCaretUpdate

    private void tblLivrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLivrosMouseClicked
        // TODO add your handling code here:
        setar_campos();
    }//GEN-LAST:event_tblLivrosMouseClicked

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        // TODO add your handling code here:
        int setar = tblLivros.getSelectedRow(); // Obtém a linha selecionada na tabela
        if (setar != -1) {
            long id = (Long) tblLivros.getModel().getValueAt(setar, 0); // Obtém o ID do livro da tabela

            JPADao jpd = new JPADao();

            // Verifica se o livro tem empréstimos ativos
            if (jpd.EmprestimosAtivos(id)) {
                JOptionPane.showMessageDialog(this, "Este Livro não pode ser excluído porque ainda possui empréstimos ativos.");

                txtTitulo.setText("");
                txtAutor.setText("");
                txtAssunto.setText("");
                txtEditora.setText("");
                btnAdicionar.setEnabled(true);
                return;
            }

            int confirm = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja excluir este Livro?", "Confirmação", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                try {
                    jpd.excluirlivro(id);
                    JOptionPane.showMessageDialog(this, "Livro excluído com sucesso!");

                    txtTitulo.setText("");
                    txtAutor.setText("");
                    txtAssunto.setText("");
                    txtEditora.setText("");
                    btnAdicionar.setEnabled(true);

                    atualizarTblLivros();
                } catch (Exception e) {

                    JOptionPane.showMessageDialog(this, "Erro ao excluir Livro: " + e.getMessage());

                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um Livro para excluir.");
        }


    }//GEN-LAST:event_btnDeletarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable tblLivros;
    private javax.swing.JTextField txtAssunto;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtEditora;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtPesquisarLivro;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables

}
